export const channelGroupFilter = {isDeleted: false};
export const channelFilter = {isDeleted: false};
export const userFilter = {isActive: true};
export const fanGroupFilter = {isDeleted: false};
export const sportFilter = {isHidden: false};
export const gamePartnerFilter = {isHidden: false};
export const gameReminderFilter = {reminderSent: false};
export const photoTypes = ['1024', '200sq', '640x360'];
export const gamePartnersWithIcons = ['espn', 'siriusxm', 'mlbtv', 'nhltv'];
